name: Restrict Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != "stage" ]]; then
            echo "Pull requests to main are only allowed from stage!"
            exit 1
          fi
